management:
  contextPath: /management
security:
  basic:
    enabled: false
spring:
  hadoop:
    resourceManagerHost: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/glennrenfro
    username: glennrenfro
    password: 
    driverClassName: org.postgresql.Driver
  database:
    driverClassName: org.postgresql.Driver
fixedDelay: 1000
thevalueyouseek: base
format: yyyy

