server:
  port: 9393
management:
  contextPath: /management
security:
  basic:
    enabled: false
spring:
  hadoop:
    resourceManagerHost: localhost
fixedDelay: 1000
thevalueyouseek: base
format: yyyy
spring:
  datasource:
    driverClassName=org.postgresql.Driver
