server:
  port: 9393
management:
  contextPath: /management
security:
  basic:
    enabled: false
spring:
  hadoop:
    resourceManagerHost: localhost
  datasource:
    url: jdbc:hsqldb:hsql://asdfas:9101
#    password: oogabooga
#    driverClassName: org.postgresql.Driver
fixedDelay: 1000
thevalueyouseek: base
format: yyyy

